name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install

      - name: Run frontend linting
        run: pnpm run lint
        continue-on-error: true

      - name: Run frontend type check
        run: pnpm run type-check
        continue-on-error: true

      - name: Build frontend
        run: pnpm run build

      - name: Run Rust tests
        run: |
          cd src-tauri
          cargo test

      - name: Run Rust clippy
        run: |
          cd src-tauri
          cargo clippy -- -D warnings
        continue-on-error: true

      - name: Test Tauri build
        run: |
          cd src-tauri
          cargo build --release
